### ISSUE TITLE
Please also upload build version

### ISSUE THREAD

**Issue by ypkkhatri** [mroach/barcode-simulator#3]
Hi,

Please also upload build version or setup file, I want to use your application but I need to install Visual Studio to build project, that's odd.

I hope your application will resolve my issue

Thanks

**Comment by mroach** [comment]
https://github.com/mroach/barcode-simulator/releases/download/1.0.5.0/BarcodeSimulator.exe

**Comment by rezagio** [comment]
10x a ton
