### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by FrederikSchaff** [mroach/barcode-simulator#6]
I would really like to use this app which looks very promissing, but unfortunately you did not provide any licence so I am not even sure if I am allowed to use it "as is". 

Could you perhaps add a licence? See also the discussion here: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by mroach** [comment]
You're absolutely allowed to use it. I added the MIT license which is about as permissive as it gets. Have fun :)
